### ISSUE TITLE
新功能建议： 简化 _config.yml 并使用 _config.kratos-rebirth.yml 存放推荐设置

### ISSUE THREAD

**Issue by ghost** [Candinya/Kratos-Rebirth#131]
1. **您的新功能建议是由使用时出现的不便引发的吗？** [Y]

根据 [Hexo文档](https://hexo.io/docs/configuration.html) , hexo 的站点配置文件 , 主题手动配置文件和主题自带配置文件是进行**合并**的。

> Hexo 在合并主题配置时，Hexo 配置文件中的 `theme_config` 的优先级最高，其次是 `_config.[theme].yml` 文件，最后是位于主题目录下的 `_config.yml` 文件。

这导致用户实际想(通过删除主题手动配置文件中的对应项)**删除**的设置被主题自带配置文件**覆盖**, 从而**显示默认**配置文件的效果.

<details>
    <summary>举例: Top Menu 顶部导航栏配置</summary><p>

用户只修改了 `site_folder/_config.kratos-rebirth.yml` :

```
menu:
  index: /
  archives: /archives/
  sites:
    submenu: true
    Vercel: https://vercel.app
    4everland: https://4everland.app

label:
  index: <i class="fa fa-home"></i>Home
  archives: <i class="fa fa-file"></i>Posts
  sites:
    submenu: <i class="fa fa-link"></i>Alternative
    Vercel: <i class="fa fa-vimeo"></i>Vercel
    4everland: <i class="fa fa-laptop"></i>4everland
```

主题自带配置文件 `site_folder/node_modules/hexo-theme-kratos-rebirth/_config.yml` 未进行修改:

```
menu:
  index: /
  archives: /archives/
  friends: /friends/
  sites:
    submenu: true
    author: https://candinya.com
    project: https://github.com/Candinya/Kratos-Rebirth

label:
  index: <i class="fa fa-home"></i>首页
  archives: <i class="fa fa-file"></i>档案馆
  friends: <i class="fa fa-paw"></i>好伙伴
  sites:
    submenu: <i class="fa fa-link"></i>链接
    author: 作者博客
    project: 项目链接
```

渲染时仍产生推荐配置中的 `好伙伴` `作者博客` `项目链接` 等菜单链接, 意味着对应的 `friends` 等项被合并了而没有如预期一样被删除.

![图片](https://user-images.githubusercontent.com/103689666/172057654-a8de41c8-8399-485b-abca-18f84a5cd228.png)
</p></details>

2. **请描述您所设想的功能或是解决方案**

在主题模块的 `_config.yml` 中只进行基础设置, 将推荐设置放在 `_config.kratos-rebirth.yml` 中, 并引导用户直接复制 `_config.kratos-rebirth.yml` 进行修改. 

3. **补充内容:**

一个无关主题的问题: `hexo-blog-encrypt` 模块中涉及 `文章TOC加密` 的部分主题是否已经适配?
若没有, 我想请教下对应 `<%- post.content %>` 的代码位于哪里?
