### ISSUE TITLE
文章列表默认随机的缩略图可以使用cdn的图片麽，没具体配置参考示例

### ISSUE THREAD

**Issue by enjoyWeb** [Candinya/Kratos-Rebirth#138]
![image](https://user-images.githubusercontent.com/8252286/177477431-96419260-f4e0-4fc2-9daf-a154c447965c.png)
![image](https://user-images.githubusercontent.com/8252286/177477490-59d7f6aa-d798-442f-9ce8-b3dd41bb741a.png)
上面2个地方如何配置，比如我在七牛云有20张图片，要替换掉images/thumb/thumb_{no}.webp

**Comment by ArcticLampyrid** [comment]
首先图片必须可以通过 1,2,3,4 这种序号访问，可以有前后缀
假设您的url为
```
https://example.com/foo/bar/cover_1_suffix.png
https://example.com/foo/bar/cover_2_suffix.png
......
https://example.com/foo/bar/cover_20_suffix.png
```

旧版设定 `jsconfig.main.pic.filename` 为 `https://example.com/foo/bar/cover_{no}_suffix.png`
新版（还未发布）设定
```yaml
jsconfig:
  main:
    cover:
      baseUrl: "https://example.com/foo/bar/"
      filenameTemplate: "cover_{no}_suffix.png" 
```
