### ISSUE TITLE
Bug 回报：DevTools 无法加载源映射&博客详情页头像文件404

### ISSUE THREAD

**Issue by Viceversa0** [Candinya/Kratos-Rebirth#170]
0. **报告前须知**

- [ √] 我确认该Bug是可复现的，我会根据下面的模板提供完整详尽的复现步骤
- [ √] 我确认已认真阅读 ReadMe.md 和文档，确认描述的内容有误或是不能解决我的问题
- [ √] 我已知晓如果没有认真阅读且勾选这里所有的条目，或是没有使用此模板认真详细地描述问题，是对彼此时间的浪费，我的 issue 可能会被无解释关闭
---
1. **对Bug的描述:**
有两个问题：
 - **1、点击进入博客详情页时，“avatar.webp”文件发生404加载失败。**
 - **2、DevTools 无法加载源映射**
---
2. **复现Bug的方法:**
正常启动时，检查浏览器控制台发生错误2，进入博客详情页，发生错误1
---
3. **期望的行为:**
头像能正常显示，同时控制台不再报错

4. **相关的截图:**
![1}WQYEYDIG1HAJ7L8ZJBZGD](https://user-images.githubusercontent.com/65475003/210171836-0bb9f441-2a6c-4024-8aa9-d074122f187d.png)

![}3%}@8DR~~1I)(C _LN_756](https://user-images.githubusercontent.com/65475003/210171840-3345fe0d-6c66-4d5f-b10c-8eea5cc76110.png)
![JWN UE9VY29PPQX{U9BT14E](https://user-images.githubusercontent.com/65475003/210171851-1b5d71d7-25a9-4dc5-99e5-fb0713a5b585.png)
![4DE40BPE@MQ(BBA2}5GR09I](https://user-images.githubusercontent.com/65475003/210171857-59fef2d9-1b59-4f3e-ac0e-1594f5045450.png)

5. **运行环境(如果该Bug的产生和环境有关，例如浏览器不兼容导致):**
 - 操作系统: Windows11
 - 浏览器: Edge
 - 版本: 108.0.1462.54 (正式版本) (64 位)

6. **您的配置文件:**
```yml
site_logo: ../images/siteLogo.webp
avatarUri: ../images/avatar.webp

topMenu:
  - label: 首页
    icon: home
    url: /
  - label: 档案馆
    icon: file
    url: /archives/
  - label: 好伙伴
    icon: pase
    url: /friends/
  - label: 链接
    icon: link
    submenu:
      - label: 作者博客
        url: https://www.cnblogs.com/XXXXXXX/
      - label: 项目链接
        url: https://github.com/Viceversa0

vendors:
  # 常用CDN基地址:
  # https://unpkg.com/
  # https://cdn.jsdelivr.net/npm/

  # 以下一行代码指定 npm cdn 基地址，该 CDN 应该兼容 jsdelivr 使用的路径格式
  # npm_cdn: https://cdn.jsdelivr.net/npm/
  packages:
    hexo-theme-kratos-rebirth: 
      # 以下一行代码用于对某个包单独配置 cdn 基地址，使用 null 表示不从 cdn 获取此包
      # cdn_url: null
      # cdn_url: https://cdn.jsdelivr.net/npm/hexo-theme-kratos-rebirth@latest/
    aplayer:
      # 以下一行代码指定所使用的库版本
      # 默认情况下会使用主题开发组进行开发调试时所使用的版本（通常而言也是最适合的版本）
      # 因此该值不建议修改
      # 
      # 注意：如果选择其他版本，则必须配置 npm_cdn 或 为包单独配置 cdn_url 或 修改 vendors 目录，
      # 这是因为主题自带的库只含有默认版本，必须从 cdn 加载其他版本或由用户手动提供其他版本的相关文件
      #
      # 警告：随意切换版本可能造成主题无法正常工作
      # 
      # version: 1.10.1
      files:
        "dist/APlayer.min.css":
          # 以下代码用于单独对某个文件进行映射，以便于使用不符合 jsdelivr 路径格式的CDN（或其他特殊情形）
          # 使用 null 表示不重定向（默认行为）
          # relocate: null
          # relocate: https://cdn.jsdelivr.net/npm/aplayer@1.10.1/dist/APlayer.min.css

          # 以下代码用于指定 SRI 以增强安全性
          # 注意，仅有部分组件支持 SRI，不支持的组件会忽略此值
          # integrity: sha256-6Y7CJDaltoeNgk+ZftgCD9jLgmGv4xKUo8nQ0HgAwVo=

friends:
  list:
  - name: "猫猫①号"
    bio: "喵~"
    avatar: "../images/avatar.webp"
    link: "https://candinya.com"
  - name: "猫猫②号"
    bio: "喵喵~"
    avatar: "../images/avatar.webp"
    link: "https://candinya.com"
  - name: "猫猫⑨号"
    bio: "咪啪~"
    avatar: "../images/avatar.webp"
    link: "https://candinya.com"

# Post Page 文章页配置
posts:
  show_cc: false
  donate: true
  share: true
  comments: 
    provider: gitalk

gitalk:
  clientID: d36XXXXXXXXXX
  clientSecret: 59a38ceXXXXXXXXXXXXXX
  repo: gitalk-comments
  owner: Viceversa0
  admin: 
    - Viceversa0
  # distractionFreeMode: false
contact:
  # weibo: 
  mail: zh_jp2022@outlook.com
  # telegram: 
  # twitter: 
  # facebook: 
  # linkedin: 
  github: Viceversa0
```

7. **补充内容:**
 - 在下修改了“node_modules\hexo-theme-kratos-rebirth\source\images”目录中的图片，但文件名保持一致，并在该文件夹增加其他文件夹和文件
 - 在下使用的yml是作者仓库中“.demo”下的“_config.kratos-rebirth.yml”，考虑到该文件的配置项较少，又从仓库中（“Candinya / Kratos-Rebirth”）的“_config.kratos-rebirth.yml”借鉴了不少的配置项，修改后的文件如第六步所示
 - 期望得到作者的回复，谢谢！
