### ISSUE TITLE
Bug 回报：使用gitalk作为评论系统时以url_for(page.path)作为id可能会因为issues lable过长导致创建评论区失败

### ISSUE THREAD

**Issue by jht3QAQ** [Candinya/Kratos-Rebirth#193]
### 报告前须知

- [X] 我确认该 Bug 是可复现的，我会根据下面的模板提供完整详尽的复现步骤
- [X] 我确认已认真阅读 ReadMe.md 和 文档，确认描述的内容有误或是不能解决我的问题
- [X] 我已知晓如果没有认真阅读且勾选这里所有的条目，或是没有使用此模板认真详细地描述问题，是对彼此时间的浪费，我的 issue 可能会被无解释关闭

### 安装方式

Git clone 项目仓库至 themes 目录下

### 对 Bug 的描述

使用gitalk作为评论系统时以url_for(page.path)作为id可能会因为issues lable过长导致创建评论区失败

gitalk会使用id作为github评论区issue的label 如果label长度超过50则会创建失败

### 复现的方法

起一个超长名字的文章(带中文的话url编码后效果更加明显) 然后使用gitalk创建评论区即可复现问题

### 期望的行为

能够正确创建评论区

### 运行环境

https://github.com/Candinya/Kratos-Rebirth/tree/1df398c5a3d0aa112aff1649a2d98e0898664f84

### 主题配置文件

```yaml
gitalk:
  clientID: 'GitHub Application Client ID'
  clientSecret: 'GitHub Application Client Secret'
  repo: 'jht3QAQ.github.io'
  owner: 'jht3QAQ'
  admin: 
    - 'jht3QAQ'
  distractionFreeMode: false
```

### 补充内容

可以把路径算成哈希作为评论的id来修复问题 不过我实现的比较糙仅供参考就好(逃)：
https://github.com/jht3QAQ/Kratos-Rebirth/commit/640ab2290383039e507b4693221577c51335190f
