### ISSUE TITLE
数学公式显示有问题怎么办

### ISSUE THREAD

**Issue by wkzqn** [Candinya/Kratos-Rebirth#216]
行内公式$xx$和行间公式$$xx$$都显示不出来

**Comment by Candinya** [comment]
您可以试试安装使用 [hexo-filter-mathjax](https://github.com/next-theme/hexo-filter-mathjax) 这个插件

**Comment by wkzqn** [comment]
我使用的是V3

**Comment by wkzqn** [comment]
![Image](https://github.com/user-attachments/assets/31df2622-2f1d-46e4-af07-29fb7a06cf54)

执行
```
pnpm add hexo-filter-mathjax
```
之后，再添加如下的配置直接就白板了：
```
mathjax:
  tags: none # or 'ams' or 'all'
  single_dollars: true # enable single dollar signs as in-line math delimiters
  cjk_width: 0.9 # relative CJK char width
  normal_width: 0.6 # relative normal (monospace) width
  append_css: true # add CSS to pages rendered by MathJax
  every_page: false # if true, every page will be rendered by MathJax regardless the `mathjax` setting in Front-matter
  packages: # extra packages to load
  extension_options: {}
    # you can put your extension options here
    # see http://docs.mathjax.org/en/latest/options/input/tex.html#tex-extension-options for more detail
```
