### ISSUE TITLE
Mac风格代码块:高亮问题

### ISSUE THREAD

**Issue by greenhandzdl** [Candinya/Kratos-Rebirth#33]
1. **对Bug的描述:**
    奇怪的渲染

2. 可能冲突的环境：
     插件："hexo-prism-plugin": "^2.3.0"
     部分根目录配置：
``` yaml
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

prismjs:
  enable: true
  preprocess: true
  line_number: false
  tab_replace: ''

prism_plugin:
  mode: 'preprocess'
  theme: 'default'
  line_number: true   # default false
  custom_css: 'path/to/your/custom.css'     # optional
```

3. 复现过程：
  1.任意创造一个页面，写入多个较长的代码块

4. 排查过程：
  1，hexo-admin直接在线预览确认代码块是否写法正确
  2，换用官方landspace主题

**Comment by Candinya** [comment]
1. 已经确定是您没有加载prismjs的主题导致，请把`custom_css: 'path/to/your/custom.css' # optional`这一行注释掉或是删掉，因为您指定了这个选项的时候，插件不会加载prismjs 的主题，反而会去加载`path/to/your/custom.css`这个路径下的文件，但显然这个样例并不是一个有效的文件，并且主题没有针对prismjs做优化，所以导致渲染大问题；
2. 请养成大块代码使用三个反引号写成代码块的习惯，就像您提供的信息，不使用代码块的显示效果非常糟糕，我已经帮您修改过了，推荐您先尝试练习一些Markdown的常用语法，包括在数字标号后使用小数点和一个空格（而不是一个中文逗号）来分隔列表项，以避免后续可能存在的问题；
3. 对于prismjs的Mac风格适配会在后续的更新中加上，并且由于是主题样式所以会使用主题加载，也不需要单独配置custom_css（同时可以避免加载顺序可能会导致的覆盖问题）。

**Comment by greenhandzdl** [comment]
感谢

**Comment by greenhandzdl** [comment]
![Screenshot_2020-11-20-06-19-15](https://user-images.githubusercontent.com/61241103/99731145-71891f80-2af8-11eb-98f4-c37e43fca0fc.png)
总感觉这个和我想的不太一致。

**Comment by Candinya** [comment]
确实，相关部分的内容都还在调整
但为什么不试一试之前就已经调整完成的highlight.js呢

**Comment by greenhandzdl** [comment]
emmm，刚刚看了这个fatal然后就rm之前的那个版本git clone下来最新版本了，结果d出来张这样。。。

**Comment by greenhandzdl** [comment]
话说最近我看到highlight9不被支持，然后我nuc发现没有更新，这个怎么解决啊

**Comment by Candinya** [comment]
hexo默认附带安装的highlight.js是能够支持的，不需要安装第三方插件。
![image](https://user-images.githubusercontent.com/20502130/99797504-55be6180-2b6a-11eb-85f8-efad142e0b3f.png)

**Comment by greenhandzdl** [comment]
比如这个提示
![Screenshot_2020-11-20-20-15-45](https://user-images.githubusercontent.com/61241103/99799257-55739580-2b6d-11eb-99c5-8f2bf89b4f4f.png)

**Comment by greenhandzdl** [comment]
然后看了一眼上次谷歌的玄学建议，现在问题网页只有一个了？
![Screenshot_2020-11-20-20-13-45](https://user-images.githubusercontent.com/61241103/99799305-64f2de80-2b6d-11eb-9ca1-3a5dd1474129.png)

**Comment by Candinya** [comment]
1. highlight.js确实存在旧版停止继续维护的问题，您可在站点文件夹下手动运行`npm i highlight.js@10`来升级highlight.js的版本，目前测试过程中尚未发现问题。
2. Google这个建议还是太玄学（摊手

**Comment by greenhandzdl** [comment]
感觉highlight有问题，我试试忽略提醒吧
![Screenshot_2020-11-20-21-30-48](https://user-images.githubusercontent.com/61241103/99805704-e18aba80-2b77-11eb-80dd-e3d838192d18.png)

**Comment by greenhandzdl** [comment]
emmm，突然想起还有个问题。
为什么aplayer要刷新一下才能出来，不刷新好像不能加载一样。

**Comment by Candinya** [comment]
> emmm，突然想起还有个问题。
> 为什么aplayer要刷新一下才能出来，不刷新好像不能加载一样。

可能是Ajax的问题，页面内容是动态替换的，文章内aplayer插件的话估计是需要准备一个重载函数

**Comment by Candinya** [comment]
不对，页面左下角的常驻播放器在刚才测试的时候也是刷新之后才出现的（但是无法复现），看了一下aplayer容器中没有被填充内容，结合控制台的报错，怀疑是因为其它部分的js运行出现了问题进而中断了主进程，您可以尝试着检查一下有没有插件存在配置问题，或是加载顺序等导致播放器无法加载的。

**Comment by greenhandzdl** [comment]
没有配置问题了，其他插件无明显报错，且都是官方配置检查的

**Comment by greenhandzdl** [comment]
其实删cookie，问题就复现了

**Comment by greenhandzdl** [comment]
而且我觉得你可以尝试通过网页中的任何一个链接进入文章或者通过网链进入，好像加载情况也不一样

**Comment by greenhandzdl** [comment]
emmm，我发现我网站无论是评论系统还是其他的都需要刷新才能显示

**Comment by Candinya** [comment]
代码加载的问题。当执行到`twikoo.init()`时，之前的script还没有被载入，导致需要刷新才能加载。
您可以使用这样的方式来改写您的评论文件配置：
``` html
<div id="twikoo" class="post-comments"></div>
<script>
    var load_comm = () => {
        const init = () => {
            twikoo.init({ envId: '**************************' });
        }
        if (typeof twikoo == 'undefined') {
            const src = 'https://cdn.jsdelivr.net/npm/twikoo@0.2.0/dist/twikoo.all.min.js';
            $.getScript(src, init);
        } else {
            init();
        }
    };

    // 直接加载即可。有能力的话也可以自己进行Lazyload相关操作的兼容。
    window.requestIdleCallback(load_comm);
</script>
<noscript>Please enable JavaScript to view the <a href="https://twikoo.js.org/">comments powered by Twikoo.</a></noscript>

```

**Comment by greenhandzdl** [comment]
emmm，我发现我连刷新都刷不出来了

**Comment by Candinya** [comment]
那么可能是因为您的JS主进程被错误卡死了。
打开您站点，控制台真的有一系列的JS报错，建议您调整一下相关的兼容性。
如果有条件的话，还是推荐使用PC端进行开发吧。

**Comment by greenhandzdl** [comment]
我想试一下官方文档里面npm引用，但是js文件该怎么插入啊，emm

**Comment by greenhandzdl** [comment]
算了，评论系统那个坑终于过了，可以正常加载。
但是aplayer和mac代码块这几个bug什么时候好啊。

**Comment by greenhandzdl** [comment]
好吧，还是没有解决，但是从404页面点击返回可以加载出来。

**Comment by greenhandzdl** [comment]
问题是那次直接加载不出来，一个大白块了。
但是我直接输入状态稍微好了一点点，不信的话我觉得你可以测试下，emmm

**Comment by Candinya** [comment]
试试这样，刚才是因为twikoo这个关键词被ID为twikoo的element占据了（说起来我还从来没遇到过这种鬼畜的情况
``` html
<div id="tcomment" class="post-comments"></div>
<script>
    var load_comm = () => {
        const init = () => {
            twikoo.init({ envId: '*******************', el: '#tcomment' });
        }
        if (typeof twikoo == 'undefined') {
            const src = 'https://cdn.jsdelivr.net/npm/twikoo@0.2.3/dist/twikoo.all.min.js';
            $.getScript(src, init);
        } else {
            init();
        }
    };

    // 直接加载即可。有能力的话也可以自己进行Lazyload相关操作的兼容。
    window.requestIdleCallback(load_comm);
</script>
<noscript>Please enable JavaScript to view the <a href="https://twikoo.js.org/">comments powered by Twikoo.</a></noscript>
```
![image](https://user-images.githubusercontent.com/20502130/100115972-254e2e80-2eae-11eb-81ce-f85ecbebb907.png)

**Comment by greenhandzdl** [comment]
谢谢，就aplayer和如题这几个问题还没有解决了

**Comment by Candinya** [comment]
aplayer的具体原因我暂时还是不知道，也可能是目前使用的后端的问题，之后会去寻找一个更优质的后端；Mac样式的问题您 git pull 一下最新版本的代码应该会有所改善（之前是因为code块的定位方式没有显式指出，导致::before修饰块飞了）
但是Mac样式中目前由于横向滚动方式设置为整个代码块滚动，好像涉及到不少相关的结构，可能还是会有些视觉上的迷惑情况发生吧。

**Comment by greenhandzdl** [comment]
对于`git pull`
因为`hexo-git-backup`插件，所以我取消了主题origin换成了我备份的origin，所以`git pull`应该是更新不了的，emmm
我在尝试`gh`，看看gh能不能不引起之间的冲突。
还有就是能不能更新完了之后fatal下，因为我可能最近不看更新，只接受issue消息

**Comment by greenhandzdl** [comment]
话说warn和error代码块怎么弄去了，就是官方文档docx的那个黄色的

**Comment by Candinya** [comment]
``` md
{% alertbox success "成功啦o(*￣▽￣*)ブ" %}
{% alertbox danger "有危险Σ(っ °Д °;)っ" %}
{% alertbox info "有消息(・∀・(・∀・(・∀・*)" %}
{% alertbox warning "当心哦≧ ﹏ ≦" %}
```

**Comment by greenhandzdl** [comment]
嗯嗯嗯，谢谢，还有就是突然发现mac块好像没适配黑夜模式

**Comment by Candinya** [comment]
是的，代码高亮样式是让用户手动指定主题的，所以并没有做相关配色的适配。

**Comment by greenhandzdl** [comment]
话说那个更新日志的缩放怎么弄，我也想搞一个更新日志，emmm

**Comment by Candinya** [comment]
> 话说那个更新日志的缩放怎么弄，我也想搞一个更新日志，emmm

``` md
{% collapse 折叠框的标题 %}

被折叠的内容 1
被折叠的内容 2
...

{% endcollapse %}
```

**Comment by greenhandzdl** [comment]
我觉得还是换成黑夜的那个吧，白色真的太刺眼了，眼睛感觉要瞎了

**Comment by Candinya** [comment]
> 我觉得还是换成黑夜的那个吧，白色真的太刺眼了，眼睛感觉要瞎了

这个应该是您的插件设置中管理的主题？您也许可以尝试修改一下PrismJS插件相关的设置哦。

**Comment by greenhandzdl** [comment]
```
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

prismjs:
  enable: true
  preprocess: true
  line_number: false
  tab_replace: ''

prism_plugin:
  mode: 'preprocess'
  theme: 'default'
  line_number: true   # default false
  # custom_css: 'path/to/your/custom.css'     # optional
```
不是这样的吗？
