### ISSUE TITLE
Bug 回报：顶部导航栏的RSS地址点击后返回键异常

### ISSUE THREAD

**Issue by D-W-X** [Candinya/Kratos-Rebirth#58]
1. **对Bug的描述:**

当前主题的顶部导航栏应该有两种判断：
- 如果使用了相对地址，那么在本页面打开，比如已有的  `/archives/` `/friends/`
- 如果使用了绝对地址，那么在新页面打开，比如 `https://candinya.com`

如果在里面加入 RSS 地址，例如 `/atom.xml`，那么也会在本页面打开。
但是在这个页面中，可能由于没有使用到主题，因此这个页面的返回键异常，点击返回无法返回之前的页面。

2. **复现Bug的方法:**

可以使用如下的方案进行复现:
- 编辑项目的配置文件，将 Top Menu 临时改为：

```yml
...
# Top Menu 顶部导航栏配置 （具体格式请参照文档）
menu:
  index: /atom.xml
...
```

- 重新编译页面并部署。打开页面，点击 '首页'，跳转到 `https://[url]//atom.xml`
- 点击浏览器返回，发现网址变了，页面没变。
- 看，出错了吧！ 

3. **期望的行为:**
正常返回，或者跳出？

4. **运行环境(如果该Bug的产生和环境有关，例如浏览器不兼容导致):**
- windows 10, 20H2, 19042.928
- chrome: 90.0.4430.93（正式版本）（64 位）
- edge: 90.0.818.51 (官方内部版本) (64 位)
