### ISSUE TITLE
Bug 回报：关于新设置好友面问题

### ISSUE THREAD

**Issue by greenhandzdl** [Candinya/Kratos-Rebirth#59]
1. **对Bug的描述:**
该Bug导致无法正常渲染页面等等。

2. **复现Bug的方法:**
部分报错
```
ERROR Theme config load failed.
ERROR {
  err: YAMLException: bad indentation of a mapping entry (159:86)

   156 |  ...
   157 |  ...
   158 |  ...
   159 |  ...                    description: "好伙伴们在哪里~"
  ------------------------------------------^
   160 |  ...
   161 |  ...                  - name: "Talk"
```
我的修改
```
# Friends 友链相关内容
friends:
  href: "friends"
  page:
    title: "好伙伴们"
    comments: false                                                       description: "好伙伴们在哪里~"
    updated: "2021-01-18"
  list:                                                                 - name: "Talk"
    bio: "Talk"
    avatar: "../images/avatar.webp"
    link: "http://ghome.byethost10.com/"                            verify: true # 验证 每个友链的可访问性，炸了会有提示
```

3. **运行环境(如果该Bug的产生和环境有关，例如浏览器不兼容导致):**
