### ISSUE TITLE
将hexo渲染器替换为hexo-renderer-markdown-it-katex 无法渲染形如$$...$$的双$公式。

### ISSUE THREAD

**Issue by hcxx** [Candinya/Kratos-Rebirth#89]
1. **对Bug的描述:**
将hexo渲染器替换为[hexo-renderer-markdown-it-katex](https://github.com/Abreto/hexo-renderer-markdown-it-katex) 可以渲染`$...$`的公式，但是无法渲染形如`$$...$$`的双$公式。展示为纯文本

2. **复现Bug的方法:**
a. 替换官方渲染器：
```cmd
npm un hexo-renderer-marked --save
npm i hexo-renderer-markdown-it-katex --save
```
&emsp;&emsp; b. 修改主题_config.yml配置文件(实测不修改也是一样的效果)
```yml
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: false
    quotes: '“”‘’'
  plugins:
  anchors:
    level: 2
    collisionSuffix: ''
```

3. **期望的行为:**
`$$...$$`数学公式居中显示

4. **相关的截图:**
其中加粗的二进制数为`$...$`公式，双`$$...$$`公式展示如图纯文本
![](https://user-images.githubusercontent.com/44201349/138708743-02a018b4-a385-4b76-a03b-8594ce282c01.png)

5. **运行环境(如果该Bug的产生和环境有关，例如浏览器不兼容导致):**
 - 操作系统: win10 20H1
 - 浏览器: Microsoft Edge
 - 版本: 95.0.1020.30 (官方内部版本) (64 位)

6. **补充内容:**
是否需要额外配置才能生效。
